items:
- uid: System.Security
  href: System.Security.yml
  name: Security
  fullName: System.Security
  type: Namespace
  source:
    remote:
      branch: master
      repo: https://github.com/chenkennt/roslyn.git
      description: v1.0-12-gef085ea
    path: src/Compilers/Core/Portable/InternalUtilities/SuppressUnmanagedCodeSecurityAttribute.cs
    startLine: 2
  id: System.Security
