id: System.Security
href: System.Security.yaml
name:
  CSharp: Security
qualifiedName:
  CSharp: System.Security
type: Namespace
source:
  remote:
    branch: master
    repo: https://github.com/chenkennt/roslyn.git
    description: v1.0-12-gef085ea
  path: src/Compilers/Core/Portable/InternalUtilities/SuppressUnmanagedCodeSecurityAttribute.cs
  startLine: 2
