id: System.Security
yaml: api\System.Security.yaml
href: api\System.Security
name:
  CSharp: Security
qualifiedName:
  CSharp: Security
type: Namespace
source:
  remote:
    branch: master
    repo: https://github.com/chenkennt/roslyn.git
    local: C:\roslyn\
    sha1: e46ffcafeeb87a2d139b531f48416f783d9fe89d
  path: src\Compilers\Core\Portable\InternalUtilities\SuppressUnmanagedCodeSecurityAttribute.cs
  startLine: 2
